Training...
Epoch 0

Training Iterations:  12%|█████▉                                         | 1/8 [00:14<01:43, 14.79s/it]
Traceback (most recent call last):
  File "/user/as6154/dissert/gpt2.py", line 185, in <module>
    output = model(input_seq)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/as6154/dissert/gpt2.py", line 91, in forward
    output = self._backbone(inputs_embeds=embeds).last_hidden_state
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1235, in forward
    outputs = block(
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 757, in forward
    feed_forward_hidden_states = self.mlp(hidden_states)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 680, in forward
    hidden_states = self.c_fc(hidden_states)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/user/as6154/.conda/envs/diss/lib/python3.9/site-packages/transformers/pytorch_utils.py", line 104, in forward
    x = torch.addmm(self.bias, x.view(-1, x.size(-1)), self.weight)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 314.00 MiB. GPU  has a total capacity of 79.14 GiB of which 169.19 MiB is free. Process 623581 has 11.49 GiB memory in use. Including non-PyTorch memory, this process has 67.47 GiB memory in use. Of the allocated memory 62.02 GiB is allocated by PyTorch, and 4.95 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)